apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omniroute.fullname" . }}
  namespace: {{ include "omniroute.namespace" . }}
  labels:
{{ include "omniroute.labels" . | indent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.app.jwtSecret | quote }}
  API_KEY_SECRET: {{ .Values.app.apiKeySecret | quote }}
  INITIAL_PASSWORD: {{ .Values.app.initialPassword | quote }}
