apiVersion: v1
kind: Service
metadata:
  name: {{ include "omniroute.fullname" . }}
  namespace: {{ include "omniroute.namespace" . }}
  labels:
{{ include "omniroute.labels" . | indent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
{{ include "omniroute.selectorLabels" . | indent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.containerPort }}
      targetPort: http
      protocol: TCP
