apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omniroute-01-data
  namespace: omniroute-01-prod
  labels:
    app.kubernetes.io/name: omniroute
    app.kubernetes.io/part-of: omniroute
    app.kubernetes.io/instance: omniroute-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain
