apiVersion: v1
kind: ConfigMap
metadata:
  name: omniroute-01-env
  namespace: omniroute-01-prod
  labels:
    app.kubernetes.io/name: omniroute
    app.kubernetes.io/part-of: omniroute
    app.kubernetes.io/instance: omniroute-01
data:
  APP_LOG_TO_FILE: "false"
  AUTH_COOKIE_SECURE: "true"
  BASE_URL: "http://localhost:20128"
  NEXT_PUBLIC_BASE_URL: "https://omniroute.101aix.net"
  NODE_ENV: "production"
  OMNIROUTE_MIGRATIONS_DIR: "/app/migrations"
  PORT: "20128"
  REDIS_URL: "redis://omniroute-01-redis-redis-redis:6379"
