apiVersion: v1
kind: Secret
metadata:
  name: omniroute-01-secret
  namespace: omniroute-01-prod
  labels:
    app.kubernetes.io/name: omniroute
    app.kubernetes.io/part-of: omniroute
    app.kubernetes.io/instance: omniroute-01
type: Opaque
stringData:
  JWT_SECRET: "ipAn3DatSZSpAFG1TvRyy2+HE/QvTIt562b3SUHFNx2R8kvMLJImvcceVH1HtbHv"
  API_KEY_SECRET: "69c1134369a98622b3153ffee2cf31688ebac4082da30e692d2b8ab1ee61c1da"
  INITIAL_PASSWORD: "CHANGEME"
