apiVersion: v1
kind: Service
metadata:
  name: omniroute-01
  namespace: omniroute-01-prod
  labels:
    app.kubernetes.io/name: omniroute
    app.kubernetes.io/part-of: omniroute
    app.kubernetes.io/instance: omniroute-01
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: omniroute
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 20128
      targetPort: http
      protocol: TCP
